### PR TITLE
from canvas to HTML5 (with bootstrap)

### PR DESCRIPTION
**Pull request by AymericDu**
I offer a version in HTML5 (instead of canvas).
This aproach improves some points:
- The perfect sharpness of letters
- Easy selection of a box (querySelector)
- The set of CSS properties are in "style.css"
- Etc.

### CODE REVIEW

**Comment by YannDub** [comment]
I think it would be more difficult to animate the box with this implementation

**Comment by AymericDu** [comment]
I just simplify and improve the code.

**Comment by AymericDu** [comment]
I do not understand ... What are the animations that you can't do with this implementation?

**Comment by YannDub** [comment]
For example when we find a word, the letters fall

**Comment by AymericDu** [comment]
I forgot that the boxes should fall ^^

**Pull request closed without merging**
